name: gimig_gastro_application
description: made by Julian Hofmeister

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

  firebase_core: ^0.5.3
  firebase_auth: ^0.18.4+1
  cloud_firestore: ^0.14.4
  firebase_storage: ^5.2.0
  firebase_analytics: ^5.0.6
  path: ^1.7.0
  uuid: ^2.1.0

  image_picker: ^0.6.7+4
  path_provider: ^1.6.11
  numberpicker: ^1.2.1

  data_connection_checker: ^0.3.4

  provider: ^4.3.2+1

  network_to_file_image: ^2.3.6



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/
    - images/icons/
    - images/logos/

  fonts:
    - family: PlayfairDisplay
      fonts:
        - asset: fonts/PlayfairDisplay-VariableFont_wght.ttf
        - asset: fonts/PlayfairDisplay-Italic-VariableFont_wght.ttf
          style: italic

    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-SemiBold.ttf
          weight: 700